<section class="mi-sub-section sub-section l-print-fullbleed l-container l-margin-subsection-bottom-responsive-large l-margin-tile-vertical-default l-padding-tile-vertical-default l-padding-subsection-vertical-none">


    <div class=" l-s-col-4 l-m-col-8 l-s-col-last l-m-col-last l-l-col-12 l-xl-col-12 l-l-col-last l-xl-col-last">
              <div id="CardArticle19e7" class="t-uniform-height">
                 <section class="tile-card-article  t-bg-standard-10  l-template-2  l-center-align l-s-col-4 l-m-col-8 l-l-col-12 l-xl-col-12 l-display-inline-block  t-box-shadow " data-component-id="CardArticle_02_19e7" data-component-name="cardArticle" data-component-endpoint="/aries-content/v1/cardArticle.comp"> <div class="img-wrapper l-s-col-4 l-l-col-8">    <picture data-param-large="downsize=1180px:*" data-param-desktop="downsize=1024px:*" data-param-tablet="downsize=768px:*" data-param-mobile="downsize=600px:*">    <source data-srcset-large="https://cache.marriott.com/marriottassets/Loyalty/program-pages/PO-redesign-moments-sept2019-5x2.jpg?&amp;interpolation=progressive-bilinear&amp;_queryParam_ , https://cache.marriott.com/marriottassets/Loyalty/program-pages/PO-redesign-moments-sept2019-5x2.jpg?2x" media="(min-width: 1025px)">   <source data-srcset-desktop="https://cache.marriott.com/marriottassets/Loyalty/program-pages/PO-redesign-moments-sept2019-5x2.jpg?&amp;interpolation=progressive-bilinear&amp;_queryParam_ , https://cache.marriott.com/marriottassets/Loyalty/program-pages/PO-redesign-moments-sept2019-5x2.jpg?2x" media="(min-width: 769px)" srcset="https://cache.marriott.com/marriottassets/Loyalty/program-pages/PO-redesign-moments-sept2019-5x2.jpg?&amp;interpolation=progressive-bilinear&amp;downsize=1024px:* , https://cache.marriott.com/marriottassets/Loyalty/program-pages/PO-redesign-moments-sept2019-5x2.jpg?2x">  <source data-srcset-tablet="https://cache.marriott.com/marriottassets/Loyalty/program-pages/PO-redesign-moments-sept2019-5x2.jpg?&amp;interpolation=progressive-bilinear&amp;_queryParam_" media="(min-width: 601px)">  <source data-srcset-mobile="https://cache.marriott.com/marriottassets/Loyalty/program-pages/PO-redesign-moments-sept2019-5x2.jpg?&amp;interpolation=progressive-bilinear&amp;_queryParam_">  <img src="https://cache.marriott.com/marriottassets/Loyalty/program-pages/icons/transparent.png?&amp;interpolation=progressive-bilinear&amp;downsize=600px:*" alt="Woman dancing">  </picture>    </div>  <div class="title-desc-cta l-s-col-4 l-l-col-4 l-padding-left-five-quarters l-padding-right-five-quarters l-display-inline-block">  <div class="title-desc ">  <h3 class="t-extend-h2">Own the Moment</h3>    <div class="l-s-margin-bottom-none l-l-margin-bottom"> <p>Redeem for experiences: Rock out at a show. Score tickets to games. Meet a celebrity chef and more!</p> </div>  </div>   <div class="cta l-margin-bottom ">      <a class="m-button m-button-secondary-fill-alt  mi-popover" href="https://moments.marriottbonvoy.com/" target="_blank"> START DREAMING  <span aria-hidden="true" class=" t-icon-external-site"></span> <span class="is-screenreader-only">Open in a different browser tab</span>  </a>       </div>  </div>  </section>   </div>

    </div>

</section>
